/**
 * Type definitions for SuFetch MCP Server
 *
 * Provides type-safe interfaces for OpenAPI v3 specifications
 * and internal server data structures
 */

import type { OpenAPIV3 } from 'openapi-types'

// Re-export OpenAPI v3 types for convenience
export type { OpenAPIV3 }

/**
 * OpenAPI Document - the root specification object
 */
export type OpenAPIDocument = OpenAPIV3.Document

/**
 * OpenAPI Operation - represents a single API endpoint operation
 */
export type OpenAPIOperation = OpenAPIV3.OperationObject

/**
 * OpenAPI Parameter - path, query, header, or cookie parameter
 */
export type OpenAPIParameter = OpenAPIV3.ParameterObject

/**
 * OpenAPI Request Body
 */
export type OpenAPIRequestBody = OpenAPIV3.RequestBodyObject

/**
 * OpenAPI Schema - JSON Schema for request/response validation
 */
export type OpenAPISchema = OpenAPIV3.SchemaObject | OpenAPIV3.ReferenceObject

/**
 * OpenAPI Response - operation response definition
 */
export type OpenAPIResponse = OpenAPIV3.ResponseObject

/**
 * OpenAPI Security Scheme
 */
export type OpenAPISecurityScheme = OpenAPIV3.SecuritySchemeObject

/**
 * Type guard to check if a schema is a reference
 */
export function isReferenceObject(
  schema: OpenAPISchema,
): schema is OpenAPIV3.ReferenceObject {
  return '$ref' in schema
}

/**
 * Type guard to check if a schema is a non-reference schema
 */
export function isSchemaObject(
  schema: OpenAPISchema,
): schema is OpenAPIV3.SchemaObject {
  return !isReferenceObject(schema)
}

/**
 * Code example generated by the server
 */
export interface CodeExample {
  /** Import statements */
  imports: string
  /** Client setup code */
  setup: string
  /** Usage code with parameters and request */
  usage: string
  /** Complete example (imports + setup + usage) */
  fullExample: string
}

/**
 * Cached code example with timestamp
 */
export interface CachedExample {
  timestamp: number
  example: CodeExample
}

/**
 * Analysis of response structure for generating helpful code examples
 */
export interface ResponseStructure {
  /** HTTP status code */
  statusCode: number
  /** Response schema (may contain $ref or be resolved) */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  schema: any
  /** Wrapper keys in the response (e.g., ["data", "servers"]) */
  wrapperKeys: string[]
  /** Whether the response is an array */
  isArray: boolean
  /** Name of the primary resource field (e.g., "server", "action") */
  primaryResource: string | null
  /** Important fields to highlight in examples */
  importantFields: string[]
  /** Whether response has actions field */
  hasActions: boolean
}

/**
 * API metadata for list_apis tool
 */
export interface APIMetadata {
  name: string
  title: string
  version: string
  description?: string
  servers?: OpenAPIV3.ServerObject[]
}

/**
 * Endpoint search result
 */
export interface EndpointResult {
  path: string
  method: string
  operationId?: string
  summary?: string
  description?: string
  tags?: string[]
}

/**
 * Resolved schema (after $ref resolution)
 */
export type ResolvedSchema = OpenAPIV3.SchemaObject
